<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/12/02 12:12:36
sfConfig::add(array(
  'mod_performancetracker_enabled' => true,
  'mod_performancetracker_view_class' => 'sfPHP',
));
