<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/12/09 10:58:51

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=test_orangehrm_mysql',
  'username' => 'root',
  'password' => '1234abcd',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
